### ISSUE TITLE
form_info() not working

### ISSUE THREAD

**Issue by DrDiscoChimp** [dmpe/WufooR#5]
I am trying to access a list of all of the form hashes for my account so that I can create a dynamic list of forms (for a Shiny App). However, form_info() returns this error.  

Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSLRead() return error -9806

I have already initialized my name and api key, and other calls such as user_info() work.

here is my sessionInfo()

R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] curl_2.8.1   WufooR_0.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     lubridate_1.6.0  gtools_3.5.0     dplyr_0.7.3      assertthat_0.2.0 plyr_1.8.4       R6_2.2.2         RAdwords_0.1.13 
 [9] jsonlite_1.5     magrittr_1.5     httr_1.3.1       stringi_1.1.5    rlang_0.1.2      reshape2_1.4.2   gdata_2.18.0     bindrcpp_0.2    
[17] tools_3.4.1      stringr_1.2.0    glue_1.1.1       compiler_3.4.1   pkgconfig_2.0.1  bindr_0.1        tibble_1.3.4

**Comment by dmpe** [comment]
Hi, I havent used it in a while. 
and will need some time to get back to it. Might take a while. 
sorry

**Comment by dmpe** [comment]
but at least thanks for the report

**Comment by dmpe** [comment]
@DrDiscoChimp 
EDIT: Ignore

**Comment by dmpe** [comment]
@DrDiscoChimp 
So, for me it works. I have no errors or other problems when calling form_info() method. 

I can broadly suggest following: delete curl + httr and reinstall them. (and restart R as well)
Then, check again and try using debugging arguments. 

```
form_info(showRequestURL = True, debugConnection = 1L)
```
otherwise, i dont have access to mac so dont know internal stuff. But take a look on curl + openssl (+brew if you use it) . 
What helped me was also to reboot PC and R because SSL, curl and R are very noisy about such problems.

**Comment by DrDiscoChimp** [comment]
@dmpe 
Thanks for checking into this right away!
I restarted everything, and I have the most recent versions of of curl and httr. However, user_info() still does not work. As best I can tell the issue is that I dont have access to the .json url. 

Below is the feedback from debug.

> options(Wufoo_Name = "MyWufooName", Wufoo_API = "XXXX-XXXX-XXXX-XXXX")
> form_info(showRequestURL = True, debugConnection = 1L)
*   Trying 75.98.93.66...
* TCP_NODELAY set
* Connected to MyWufooName.wufoo.com (75.98.93.66) port 443 (#0)
  * WARNING: disabling hostname validation also disables SNI.
  * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  * Server certificate: *.wufoo.com
  * Server certificate: DigiCert SHA2 Secure Server CA
  * Server certificate: DigiCert Global Root CA
  > GET /api/v3/forms.json?includeTodayCount=false HTTP/1.1
  Host: MyWufooName.wufoo.com
  User-Agent: libcurl/7.54.0 r-curl/2.8.1 httr/1.3.1
  Accept-Encoding: gzip, deflate
  Accept: application/json, text/xml, application/xml, */*
    
    * HTTP 1.0, assume close after body
  < HTTP/1.0 401 Unauthorized
  < Date: Thu, 21 Sep 2017 14:03:47 GMT
  * Added cookie PHPSESSID="ljk9mpno7h9468snrd6sp9fid6" for domain wufoo.com, path /, expire 0
  < Set-Cookie: PHPSESSID=ljk9mpno7h9468snrd6sp9fid6; path=/; domain=.wufoo.com
  < Expires: Thu, 19 Nov 1981 08:52:00 GMT
  < Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  < Pragma: no-cache
  < X-Frame-Options: SAMEORIGIN
  < WWW-Authenticate: Basic realm="Wufoo Secret Lab"
  < X-UA-Compatible: IE=Edge,chrome=1
  < Content-Length: 44
  * HTTP/1.0 connection set to keep alive!
    < Connection: Keep-Alive
  < Content-Type: text/html; charset=UTF-8
  * Added cookie ep201="aKLGLM1j4J5wlA3rzXCbANTWjxQ=" for domain wufoo.com, path /, expire 1506004427
  < Set-Cookie: ep201=aKLGLM1j4J5wlA3rzXCbANTWjxQ=;Path=/;Domain=.wufoo.com;Expires=Thu, 21-Sep-2017 14:33:47 GMT
  * Added cookie ep202="mYD3zf0LX1rY2vM4o9njM3kFYvU=" for domain wufoo.com, path /, expire 1537559553
  < Set-Cookie: ep202=mYD3zf0LX1rY2vM4o9njM3kFYvU=;Path=/;Domain=.wufoo.com;Expires=Fri, 21-Sep-2018 19:52:33 GMT
  < X-Powered-By: Zathras
  < 
    * Ignoring the response-body
  * Connection #0 to host MyWufooName.wufoo.com left intact
  * Issue another request to this URL: 'https://MyWufooName.wufoo.com/api/v3/forms.json?includeTodayCount=false'
  * Found bundle for host MyWufooName.wufoo.com: 0x10200d030 [serially]
  * Re-using existing connection! (#0) with host MyWufooName.wufoo.com
    * Connected to MyWufooName.wufoo.com (75.98.93.66) port 443 (#0)
      * Server auth using Basic with user 'XXXX-XXXX-XXXX-XXXX'
      > GET /api/v3/forms.json?includeTodayCount=false HTTP/1.0
      Host: MyWufooName.wufoo.com
      Authorization: Basic TzZSRS03NE9KLVYyWkYtVzZUODpmYWtlcGFzc3dvcmQ=
        User-Agent: libcurl/7.54.0 r-curl/2.8.1 httr/1.3.1
      Accept-Encoding: gzip, deflate
      Cookie: PHPSESSID=ljk9mpno7h9468snrd6sp9fid6; ep201=aKLGLM1j4J5wlA3rzXCbANTWjxQ=; ep202=mYD3zf0LX1rY2vM4o9njM3kFYvU=
        Accept: application/json, text/xml, application/xml, */*
        
        < HTTP/1.1 200 OK
      < Date: Thu, 21 Sep 2017 14:03:47 GMT
      < Expires: 0
      < Cache-Control: must-revalidate, post-check=0, pre-check=0
      < Pragma: public
      < X-Frame-Options: SAMEORIGIN
      < Cache-Control: private
      < X-UA-Compatible: IE=Edge,chrome=1
      < Connection: close
      < Content-Type: application/json; charset=utf-8
      * Replaced cookie ep201="aKLGLM1j4J5wlA3rzXCbANTWjxQ=" for domain wufoo.com, path /, expire 1506004429
      < Set-Cookie: ep201=aKLGLM1j4J5wlA3rzXCbANTWjxQ=;Path=/;Domain=.wufoo.com;Expires=Thu, 21-Sep-2017 14:33:49 GMT
      * Replaced cookie ep202="mYD3zf0LX1rY2vM4o9njM3kFYvU=" for domain wufoo.com, path /, expire 1537559555
      < Set-Cookie: ep202=mYD3zf0LX1rY2vM4o9njM3kFYvU=;Path=/;Domain=.wufoo.com;Expires=Fri, 21-Sep-2018 19:52:35 GMT
      < X-Powered-By: Bananas and Rum
      < 
        * SSLRead() return error -9806
      * Closing connection 0
      Error in curl::curl_fetch_memory(url, handle = handle) : 
        SSLRead() return error  -9806

**Comment by dmpe** [comment]
@DrDiscoChimp 
>As best I can tell the issue is that I dont have access to the .json url.

just to clarify (for myself):

if you do `form_info(showRequestURL = True)` you should get a URL that points to the JSON file. 
If you authenticate through the browser (i.e. just go to `***.wufoo.com/admin/`, then just go to that JSON link in browser and see what it shows. 

If it shows something that you can attach (**dont forget about security and privacy!!! **), please do. It will help me. 

Now, also not going to lie: if you pay for the Wufoo, please contact them as well for help, specifically if you are already WuFoo "administrator" and ask why you cant access it. 

If you are not WuFoo admin then contact him/her. 

Very interesting that you cant access that json location. Please also check each form for the right field and form settings.

**Comment by dmpe** [comment]
thanks for the debug log, that seems to be fine.

**Comment by dmpe** [comment]
>This request returns details on all the forms **you have permission to access**.
https://wufoo.github.io/docs/?shell#all-forms

Hence please also make sure that you can access them. But i guess if you work with other, than you should have already access to it.

**Comment by DrDiscoChimp** [comment]
Well, after doing some more research with the API features, I tried a running this from the command line: curl -u "XXXX-XXXX-XXXX-XXXX":"MyWufooName" "https://MyWufooName.wufoo.com/api/v3/forms.json" - and it returned the text output. So now my code in R is 

forms = jsonlite::fromJSON(system("curl -u 'XXXX-XXXX-XXXX-XXXX':'mywufooname' 'https://mywufooname.wufoo.com/api/v3/forms.json'", intern=T))

This works for me. It returns a data frame with all the appropriate information. 

I dont know what the implications of this are though. Maybe there is an issue with my curl packages still? Maybe my auth functions are not working properly? Idrk. 

Hopefully this helps you somehow. Best of luck, and thanks again for your help.

**Comment by dmpe** [comment]
very interesting.....let me know over the email (see my profile page) if i can help you more with this. 
i have had with curl package+R rather not so much positive experiences and so will be glad to track this down. 

Thanks.
